// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byvphgvsclnfbwhmijjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5dnBoZ3ZzY2xuZmJ3aG1pamprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MDc1OTcsImV4cCI6MjA1NTE4MzU5N30.UjcdICzCAxHiG1VQa3MD6R2rZHp93U920fEYFcboFRs";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      storage: window.localStorage,
      flowType: 'pkce'
    }
  }
);